spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testapp?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: 1qaz!QAZ
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

jwt:
  secret: secretkey123
